---
- hosts: nodes
# Install Packages

  vars: 
    packages:
      - git
      - python-dev
      - python-pip
      - gcc
      - python-setuptools
      - git-core
      - python-setuptools
      - debconf-utils
    pippackages:
      - slackclient
      - py-trello
      - pyrebase
      - python-firebase

  tasks:
    - name: Set Env
      environment:
         TEAM_NAME: "510projectteam"
         BOARD_NAME: "Demo Board"
         BOT_TOKEN: "xoxb-266498254006-btD2n1TcKdi5MY6AKlPGTwnm"
         BOT_ID: "U7UEN7G06" 
         TRELLO_API_KEY: "dbf6947f87a8dcb83f090731a27e8bd4"
         TRELLO_API_SECRET: "f57a6c66081742aa5f6149d329c3581d53231c308e4cc9f78b31230ce13b3bb8"
         TRELLO_TOKEN: "414df911de9e839c8ab9838c8fa1723107fba5848e5049269d88e5e94a348f31"
         FIREBASE_API_KEY: "AIzaSyCC5OzyEqGBcGZkpyUP90qUnyCCJY8SRQ8"
         FIREBASE_AUTH_DOMAIN: "taskmangerbot.firebaseapp.com"
         FIREBASE_DATABASE_URL: "https://taskmangerbot.firebaseio.com"
         FIREBASE_STORAGE_BUCKET: "taskmangerbot.appspot.com"
         GMAIL_ID: 'bot510project@gmail.com'
         GMAIL_PASS: 'simtiaz1234'
    - name: Install packages
      apt:
        pkg: "{{ item }}"
        state: installed
        update_cache: yes
      with_items: "{{packages}}"
      become: yes
    - debug:
        msg: "{{ item }}"
      with_items: "{{packages}}"

    - name: PIP install python packages
      pip: 
        name: "{{ item }}"
      with_items: "{{pippackages}}"
      become: yes


