---
- hosts: nodes
# Clone Github
# generate github keys in that directory
#ssh-keygen -t rsa -b 4096 -C "xfu7@ncsu.edu"
#ssh-agent bash -c 'ssh-add /home/ubuntu/.ssh/id_rsa; git clone git@github.ncsu.edu:yhu22/CSC510_F17_Project.git'
  vars:
    dest_dir: /home/ubuntu/dev
    gh_repo: git@github.ncsu.edu:yhu22/CSC510_F17_Project.git


  tasks:
    - name: Copy ssh public key to the folder
      copy:
        src: /home/ubuntu/.ssh/id_rsa.pub
        dest: /home/ubuntu/.ssh/id_rsa.pub

    - name: Copy ssh private to the folder
      copy:
        src: /home/ubuntu/.ssh/id_rsa
        dest: /home/ubuntu/.ssh/id_rsa

    - name: Setup the Git repo
      git: repo={{ gh_repo }}
           dest={{ dest_dir }}
           accept_hostkey=yes
           key_file="/home/ubuntu/.ssh/id_rsa"
      become: yes


