---
- hosts: nodes
  environment:
     TEAM_NAME: 510projectteam
     BOARD_NAME: 'Demo Board'
     BOT_TOKEN: xoxb-266498254006-btD2n1TcKdi5MY6AKlPGTwnm
     BOT_ID: U7UEN7G06 
     TRELLO_API_KEY: dbf6947f87a8dcb83f090731a27e8bd4
     TRELLO_API_SECRET: f57a6c66081742aa5f6149d329c3581d53231c308e4cc9f78b31230ce13b3bb8
     TRELLO_TOKEN: 414df911de9e839c8ab9838c8fa1723107fba5848e5049269d88e5e94a348f31
     FIREBASE_API_KEY: AIzaSyCC5OzyEqGBcGZkpyUP90qUnyCCJY8SRQ8
     FIREBASE_AUTH_DOMAIN: taskmangerbot.firebaseapp.com
     FIREBASE_DATABASE_URL: https://taskmangerbot.firebaseio.com
     FIREBASE_STORAGE_BUCKET: taskmangerbot.appspot.com
     GMAIL_ID: bot510project@gmail.com
     GMAIL_PASS: simtiaz1234
  vars:
    envVars:
        - TEAM_NAME
        - BOARD_NAME
        - BOT_TOKEN
        - BOT_ID
        - TRELLO_API_KEY
        - TRELLO_API_SECRET
        - TRELLO_TOKEN
        - FIREBASE_API_KEY
        - FIREBASE_AUTH_DOMAIN
        - FIREBASE_DATABASE_URL
        - FIREBASE_STORAGE_BUCKET
        - GMAIL_ID
        - GMAIL_PASS
  tasks:
    - name: Test Env
      command: python -c "import os; print os.environ.get('{{ item }}')"
      #command: python -c "import os; print os.environ.get('{{ item }}')" > envTest.out
      with_items: envVars
      register: output
    - debug: var=item.stdout
      with_items: output.results
